### ISSUE TITLE
NPM error

### ISSUE THREAD

**Issue by gsharp021** [nhnent/toast-ui.vue-editor#10]
1.0.0 - 1.0.4

## Test Environment

Linux

## Current Behavior

When running npm install after including this in my package.json, the install will hang for 10-20 minutes and then I get the following error:
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t git://github.com/adobe-webplatform/eve.git
npm ERR! 
npm ERR! undefined
npm ERR! exited with error code: 128

It's been this way for a couple of days.  Any work around or fix?

```js
// Write example code
```

**Comment by sohee-lee7** [comment]
@gsharp021 Your linux environment does not support git protocol (`git://`). You change your git config for work around. This is for change url from `git://` to `https://`.
```
git config --global url."https://".insteadOf git://
```
