### ISSUE TITLE
Cannot use 'invoke' inside load event handler

### ISSUE THREAD

**Issue by rodumani** [nhnent/toast-ui.vue-editor#11]
## Version

tui-editor 1.2.9
@toast-ui/vue-editor 1.0.4

## Test Environment

Chrome 72.0.3626.119
macOS Mojave 10.14.1

## Current Behavior

When I try to use `invoke` method to call the method of tui.editor inside load event handler, 

`Error in v-on handler: "TypeError: Cannot read property 'getCodeMirror' of null"` occurs.

`invoke` works well except load error handler. 

```js
// Write example code
<template>
    <editor
    ref="tuiEditor"
    @load="onEditorLoad"
    />
</template>
<script>
import { Editor } from '@toast-ui/vue-editor'

export default {
    components: {
        'editor': Editor
    },
    methods: {
        onEditorLoad() {
            const cm = this.$refs.tuiEditor.invoke('getCodeMirror')
        },
    }
};
</script>
```

It seems that `load` event has some timing issue that event handler called before registering `this.editor` property at line 100 of Editor.vue

https://github.com/nhnent/toast-ui.vue-editor/blob/00bb7b3f533dd6b9fe4fd145128ff5939839838c/src/Editor.vue#L100

## Expected Behavior

`load` event should emit after component is ready to go.

**Comment by sohee-lee7** [comment]
@rodumani tui.editor emit 'load' event in the constructor function. So when use 'load' event, you can get instance by parameter of handler like this.
```js
        onEditorLoad(instance) {
            const cm = instance.getCodeMirror();
        },
```
It need more discussion about when load event occur. Therefore use parameter that is editor instance when use 'load' event.

**Comment by rodumani** [comment]
Sorry for the late response. It works well. 

However, I think it should be written at the document 😃
