### ISSUE TITLE
NPM Install fails with npm ERR! package.json Non-registry package missing package.json: squire-rte@github:sohee-lee7/Squire#b1e0e1031fa18912d233c204cbe7c7fae4a42621

### ISSUE THREAD

**Issue by MstaceyMWAM** [nhnent/toast-ui.vue-editor#14]
## Version
Latest from NPM

## Test Environment
Windows

## Current Behavior
npm install --save @toast-ui/vue-editor

Gives error:
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: squire-rte@github:sohee-lee7/Squire#b1e0e1031fa18912d233c204cbe7c7fae4a42621.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mstacey\AppData\Roaming\npm-cache\_logs\2019-03-11T10_10_15_631Z-debug.log

All other packages install fine, so it doesn't appear to be a local NPM install issue

## Expected Behavior
NPM install works

**Comment by MstaceyMWAM** [comment]
Attached from debug.log on a new empty install:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   '@toast-ui/vue-editor' ]
2 info using npm@5.6.0
3 info using node@v8.10.0
4 verbose npm-session 0708c436bcb15889
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 http://p-eu-npm/npm/MWNpm/@toast-ui%2fvue-editor 2306ms
8 silly pacote tag manifest for @toast-ui/vue-editor@latest fetched in 2397ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule @toast-ui/vue-editor@1.0.4 checking installable status
14 http fetch GET 200 http://p-eu-npm/npm/MWNpm/tui-editor 701ms
15 silly pacote range manifest for tui-editor@^1.3.0 fetched in 707ms
16 silly resolveWithNewModule tui-editor@1.3.2 checking installable status
17 http fetch GET 200 http://p-eu-npm/npm/MWNpm/@types%2fcodemirror 1036ms
18 silly pacote version manifest for @types/codemirror@0.0.71 fetched in 1040ms
19 silly resolveWithNewModule @types/codemirror@0.0.71 checking installable status
20 http fetch GET 200 http://p-eu-npm/npm/MWNpm/resize-observer-polyfill 1098ms
21 silly pacote range manifest for resize-observer-polyfill@^1.5.0 fetched in 1103ms
22 silly resolveWithNewModule resize-observer-polyfill@1.5.1 checking installable status
23 http fetch GET 200 http://p-eu-npm/npm/MWNpm/plantuml-encoder 1114ms
24 silly pacote range manifest for plantuml-encoder@^1.2.5 fetched in 1157ms
25 silly resolveWithNewModule plantuml-encoder@1.2.5 checking installable status
26 http fetch GET 200 http://p-eu-npm/npm/MWNpm/jquery 1172ms
27 silly pacote range manifest for jquery@^3.3.1 fetched in 1183ms
28 silly resolveWithNewModule jquery@3.3.1 checking installable status
29 http fetch GET 200 http://p-eu-npm/npm/MWNpm/@types%2fjquery 1225ms
30 http fetch GET 200 http://p-eu-npm/npm/MWNpm/markdown-it 1232ms
31 http fetch GET 200 http://p-eu-npm/npm/MWNpm/tui-code-snippet 76ms
32 silly pacote range manifest for @types/jquery@^3.3.29 fetched in 1243ms
33 silly resolveWithNewModule @types/jquery@3.3.29 checking installable status
34 silly pacote range manifest for markdown-it@^8.4.0 fetched in 1244ms
35 silly resolveWithNewModule markdown-it@8.4.2 checking installable status
36 silly pacote range manifest for tui-code-snippet@^1.5.0 fetched in 85ms
37 silly resolveWithNewModule tui-code-snippet@1.5.0 checking installable status
38 http fetch GET 200 http://p-eu-npm/npm/MWNpm/highlight.js 1250ms
39 silly pacote range manifest for highlight.js@^9.12.0 fetched in 1271ms
40 silly resolveWithNewModule highlight.js@9.15.6 checking installable status
41 http fetch GET 200 http://p-eu-npm/npm/MWNpm/tui-color-picker 88ms
42 silly pacote range manifest for tui-color-picker@^2.2.1 fetched in 91ms
43 silly resolveWithNewModule tui-color-picker@2.2.2 checking installable status
44 http fetch GET 200 http://p-eu-npm/npm/MWNpm/tui-chart 168ms
45 silly pacote range manifest for tui-chart@^3.0.1 fetched in 171ms
46 silly resolveWithNewModule tui-chart@3.6.1 checking installable status
47 http fetch GET 200 http://p-eu-npm/npm/MWNpm/to-mark 327ms
48 silly pacote range manifest for to-mark@^1.1.2 fetched in 336ms
49 silly resolveWithNewModule to-mark@1.1.3 checking installable status
50 http fetch GET 200 http://p-eu-npm/npm/MWNpm/codemirror 1380ms
51 silly pacote range manifest for codemirror@^5.33.0 fetched in 1477ms
52 silly resolveWithNewModule codemirror@5.44.0 checking installable status
53 http fetch GET 200 http://p-eu-npm/npm/MWNpm/@types%2fmarkdown-it 1711ms
54 silly pacote version manifest for @types/markdown-it@0.0.7 fetched in 1713ms
55 silly resolveWithNewModule @types/markdown-it@0.0.7 checking installable status
56 silly fetchPackageMetaData error for squire-rte@github:sohee-lee7/Squire#b1e0e1031fa18912d233c204cbe7c7fae4a42621 Non-registry package missing package.json: squire-rte@github:sohee-lee7/Squire#b1e0e1031fa18912d233c204cbe7c7fae4a42621.
57 silly saveTree delnow@1.0.0
57 silly saveTree `-- @toast-ui/vue-editor@1.0.4
57 silly saveTree   `-- tui-editor@1.3.2
57 silly saveTree     +-- @types/codemirror@0.0.71
57 silly saveTree     +-- @types/jquery@3.3.29
57 silly saveTree     +-- @types/markdown-it@0.0.7
57 silly saveTree     +-- codemirror@5.44.0
57 silly saveTree     +-- highlight.js@9.15.6
57 silly saveTree     +-- jquery@3.3.1
57 silly saveTree     +-- markdown-it@8.4.2
57 silly saveTree     +-- plantuml-encoder@1.2.5
57 silly saveTree     +-- resize-observer-polyfill@1.5.1
57 silly saveTree     +-- to-mark@1.1.3
57 silly saveTree     +-- tui-chart@3.6.1
57 silly saveTree     | `-- tui-code-snippet@1.5.0
57 silly saveTree     +-- tui-code-snippet@1.5.0
57 silly saveTree     `-- tui-color-picker@2.2.2
58 verbose stack Error: Non-registry package missing package.json: squire-rte@github:sohee-lee7/Squire#b1e0e1031fa18912d233c204cbe7c7fae4a42621.
58 verbose stack     at BB.join (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\finalize-manifest.js:160:23)
58 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
58 verbose stack     at Holder$5._callFunction (eval at generateHolderClass (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\join.js:92:16), <anonymous>:14:44)
58 verbose stack     at Holder$5.checkFulfillment (eval at generateHolderClass (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\join.js:92:16), <anonymous>:29:30)
58 verbose stack     at Promise.eval (eval at thenCallback (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\join.js:14:16), <anonymous>:6:20)
58 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:566:21)
58 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
58 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
58 verbose stack     at Promise._fulfill (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:638:18)
58 verbose stack     at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\nodeback.js:42:21)
58 verbose stack     at emitNone (events.js:111:20)
58 verbose stack     at Object.emit (events.js:208:7)
58 verbose stack     at Object.Parser.on._ (C:\Program Files\nodejs\node_modules\npm\node_modules\tar\lib\parse.js:75:14)
58 verbose stack     at emitTwo (events.js:126:13)
58 verbose stack     at Object.emit (events.js:214:7)
58 verbose stack     at Object.[emit] (C:\Program Files\nodejs\node_modules\npm\node_modules\tar\lib\parse.js:229:12)
59 verbose cwd C:\Git\delnow
60 verbose Windows_NT 6.1.7601
61 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "@toast-ui/vue-editor"
62 verbose node v8.10.0
63 verbose npm  v5.6.0
64 error code ENOPACKAGEJSON
65 error package.json Non-registry package missing package.json: squire-rte@github:sohee-lee7/Squire#b1e0e1031fa18912d233c204cbe7c7fae4a42621.
66 error package.json npm can't find a package.json file in your current directory.
67 verbose exit [ 1, true ]

**Comment by sohee-lee7** [comment]
https://github.com/nhnent/tui.editor/issues/433

**Comment by sohee-lee7** [comment]
Discussions on this issue were made in the tui.editor. So I will close this issue.
