### ISSUE TITLE
How can I use exts with Viewer?

### ISSUE THREAD

**Issue by rodumani** [nhnent/toast-ui.vue-editor#16]
## Version

`@toast-ui/vue-editor` 1.0.4
`tui-editor` 1.3.3

## Test Environment

Chrome 73.0.3683.75

## Current Behavior

`Editor` has `options` prop, but `Viewer` does not have `options` prop so that I cannot define `exts` to use on `Viewer`.

## Expected Behavior

Please add `options` prop or `exts` prop to `Viewer`

**Comment by sohee-lee7** [comment]
@rodumani I'm sorry I didn't add an extension option to the viewer. This issue will be fixed as soon as possible.

**Comment by rodumani** [comment]
I was trying to fix it by myself to contribute as PR.

However, it's not working because of tui-editor's Viewer's issue which cannot use extension. https://github.com/nhnent/tui.editor/issues/414

**Comment by sohee-lee7** [comment]
@rodumani We should highly praise your efforts. As you mentioned, there is an issue in Viewer. So first of all, I'll release the extension to work in the Viewer soon. Please wait a little longer.
