### ISSUE TITLE
How can I use color picker on vue-editor?

### ISSUE THREAD

**Issue by isoming** [nhnent/toast-ui.vue-editor#19]
## Version
1.1.1

## Test Environment
MacOS

## Current Behavior
I couldn't find the guide for setting text color. Can I use font color changing on vue-editor? If so, how can I?

**Comment by sohee-lee7** [comment]
Color picker is implemented by extension of editor so you need import `tui-editor/dist/tui-editor-extColorSyntax` and then set `exts`.

```
import 'tui-editor/dist/tui-editor-extColorSyntax';
```

```html
<editor :options="editorOptions" />
```
```js
editorOptions: {
        exts: [
          'colorSyntax'
        ]
      }
```

**Comment by isoming** [comment]
@sohee-lee7 Thanks!!
