### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by sayi65** [nhnent/toast-ui.vue-editor#27]
when npm install get error

## Test Environment
npm install --save @toast-ui/vue-editor

## Current Behavior

```js
67 verbose node v10.8.0
68 verbose npm  v6.9.0
69 error path git
70 error code ENOENT
71 error errno ENOENT
72 error syscall spawn git
73 error enoent Error while executing:
73 error enoent undefined ls-remote -h -t ssh://git@github.com/sohee-lee7/Squire.git
73 error enoent
73 error enoent
73 error enoent spawn git ENOENT
74 error enoent This is related to npm not being able to find a file.
75 verbose exit [ 1, true ]
```

**Comment by sohee-lee7** [comment]
I think your environment is blocked git protocol.
(reference: https://stackoverflow.com/questions/4891527/git-protocol-blocked-by-company-how-can-i-get-around-that/10729634#10729634)
Try to config of git.

```
git config --global url."https://github".insteadOf github:
```

Please refer to https://github.com/nhn/tui.editor/issues/433

**Comment by sayi65** [comment]
This problem has been resolved
I was not install git command line in Windows 10.
my proposal is  dont use git path in npm repository.
How about use https .
