### ISSUE TITLE
How to get HTML Export

### ISSUE THREAD

**Issue by orhanmusellim** [nhnent/toast-ui.vue-editor#28]
i'm using this pack with nuxt.js. Everything work fine but just export how to make HTML ?

This example content: 
**qweqeqweqeqewq** ## **123123123123123** > **qweqweqeqeqeqweqeqeqwe** - - - * [x] qwe * [x] qweqw * [ ] eqwe * [ ] qwe * [x] 12 * [x] 3123 * [x] 123 * [ ] 123 | qweqw | eqeq | wqeqw | qweqwe | | ----- | ---- | ----- | ------ | | qweqwe | qeq | weqwe

**Comment by sohee-lee7** [comment]
Use `invoke` method with `getHtml`.
Please refer to the example below.
https://github.com/nhn/toast-ui.vue-editor#method

**Comment by orhanmusellim** [comment]
Thanks. Work now.
