### ISSUE TITLE
how to switch from the editor to the viewer

### ISSUE THREAD

**Issue by nicolasvahidzein** [nhnent/toast-ui.vue-editor#29]
hello since we cannot use the editor and the viewer component in the same window because of the error caused how do we switch from one to the other? Thanks.

**Comment by sohee-lee7** [comment]
Because the editor and viewer are independent components, we do not provide the ability to switch between the editor and viewer. This feature is implemented by user.

If you need just preview, you can use `previewStyle` option as `tab`.

**Comment by nicolasvahidzein** [comment]
ok i will try that thank you. So just do

previewStyle="tab"

?

**Comment by sohee-lee7** [comment]
like this
https://github.com/nhn/toast-ui.vue-editor/blob/65b066ce21ef1a6f32b7245ebab72b3a7a781bc7/stories/editor.stories.js#L97

**Comment by nicolasvahidzein** [comment]
i'm not talking about the markdown editor, i'm talking about the viewer itself, how do i transform the editor in a viewer since i cannot have the viewer and the editor on the same page. I hope this clears up what i was trying to accomplish.

**Comment by sohee-lee7** [comment]
There is no way to switch from the viewer to the editor and vice versa.

**Comment by nicolasvahidzein** [comment]
So i was finally able to do it actually and it works great. You need to place each element in a v-if div and i was able to load the editor and the viewer on the same page which is what i wanted. 

If users want to edit a note in the app they go into edit mode, if not they stay in viewer mode and they can see the HTML formatter content like it should be. 

It's beautiful, thanks sir.
