### ISSUE TITLE
Localization feature

### ISSUE THREAD

**Issue by zymawy** [nhnent/toast-ui.vue-editor#4]
### Feature Request,

Hi, Thank, You For Such Fabulous Component.
Wouldn't Nice If You Can Localiza The Component To Support Any Language?

**Comment by sohee-lee7** [comment]
Did you request to change language? You can set language like this:
```js
const options = {
     language: 'zh'
}
```
If you want to add more language, you can do it. (like this : https://github.com/nhnent/tui.editor/pull/334)
