### ISSUE TITLE
Q: Is there a 'viewer' component?  

### ISSUE THREAD

**Issue by dantrevino** [nhnent/toast-ui.vue-editor#6]
## Version
1.0.2

## Test Environment
Chrome, Linux

## Current Behavior
Looking for a feature to display rendered view
```js
<viewer v-vmodel="inputText" />
```

## Expected Behavior
viewer rendered input

**Comment by sohee-lee7** [comment]
Viewer does not support `v-model`. Viewer can render input text using `value`.
```html
<viewer :value="inputText" />
```

**Comment by dantrevino** [comment]
That makes more sense. I didn't see this in the docs.   Thank you!
